export const docsIndex = [
  {
    href: "/developers",
    title: "Start building",
    group: "Start here",
    description: "Overview, integration setup, AI prompt, issuer and discovery",
  },
  {
    href: "/developers/quickstart",
    title: "Add sign-in",
    group: "Start here",
    description:
      "Quickstart with Node.js, PKCE, callback, state, nonce and session",
  },
  {
    href: "/developers/quickstart#register",
    title: "Register your app",
    group: "On this page",
    description: "AUID client ID and exact redirect URI",
  },
  {
    href: "/developers/quickstart#authorize",
    title: "Start authorization",
    group: "On this page",
    description: "Generate verifier, S256 challenge, state and nonce",
  },
  {
    href: "/developers/quickstart#callback",
    title: "Handle the callback",
    group: "On this page",
    description: "Exchange code and handle errors or denied consent",
  },
  {
    href: "/developers/quickstart#verify",
    title: "Verify identity",
    group: "On this page",
    description: "ID token, JWKS, issuer, audience, expiry and sub",
  },
  {
    href: "/developers/quickstart#session",
    title: "Create your session",
    group: "On this page",
    description: "Cookies, account linking, production checklist",
  },
  {
    href: "/developers/permissions", title: "Declared permissions", group: "Build & explore",
    description: "App contexts, templates, typed bindings, wildcards, discovery and delegation",
  },
  ...[
    ["contexts", "Permission contexts", "Owner app AUID and system defaults"],
    ["declarations", "Templates and bindings", "Typed parameters, constraints and metadata"],
    ["wildcards", "Parameter wildcards", "Allowed wildcards and token scopes"],
    ["picker", "Delegation picker", "Tree, search, describe, check and delegate"],
    ["oauth", "OAuth permission scopes", "System context, consent and native tokens"],
    ["api", "Permission API", "GraphQL queries and mutations"],
    ["errors", "Permission errors", "Validation failures and app validator unavailability"],
    ["migration", "Permission migration", "Replace free-form grants and deploy the engine"],
  ].map(([anchor, title, description]) => ({ href: `/developers/permissions#${anchor}`, title, description, group: "On this page" })),
  {
    href: "/developers/become-an-app", title: "Become an app", group: "Build & explore",
    description: "Publish declarations, combination invariants, dynamic validators and cache invalidation",
  },
  ...[
    ["publish", "Publish declarations", "Owner authorization, republishing and versions"],
    ["parameters", "Parameter definitions", "Types, constraints and display metadata"],
    ["validator", "Dynamic validation", "POST validate protocol, timeout, retry and cached verdicts"],
    ["search", "Dynamic value search", "POST search protocol and degraded raw input"],
    ["invalidate", "Invalidate verdicts", "notifyValidationChanged after app data changes"],
  ].map(([anchor, title, description]) => ({ href: `/developers/become-an-app#${anchor}`, title, description, group: "On this page" })),
  {
    href: "/developers/reference",
    title: "API reference",
    group: "Build & explore",
    description: "OAuth 2.0 and OpenID Connect endpoints",
  },
  {
    href: "/developers/reference#authorize",
    title: "Authorization parameters",
    group: "On this page",
    description: "GET /authorize request fields and scopes",
  },
  {
    href: "/developers/reference#token",
    title: "Token exchange",
    group: "On this page",
    description: "POST /oauth/token errors invalid_grant invalid_client",
  },
  {
    href: "/developers/reference#tokens",
    title: "Tokens & lifetimes",
    group: "On this page",
    description:
      "Access token, refresh rotation, ID token and native AXUS token",
  },
  {
    href: "/developers/reference#refresh",
    title: "Refresh & logout",
    group: "On this page",
    description: "offline_access, rotation, session logout and disconnect",
  },
  {
    href: "/developers/reference#userinfo",
    title: "Profile & claims",
    group: "On this page",
    description: "Userinfo, sub, name, synthetic email and scopes",
  },
  {
    href: "/developers/reference#revoke",
    title: "Revoke authorization",
    group: "On this page",
    description: "Disconnect app POST /oauth/revoke",
  },
  {
    href: "/developers/reference#introspect",
    title: "Introspection",
    group: "On this page",
    description: "Check token active status",
  },
  {
    href: "/developers/reference#graphql",
    title: "GraphQL proxy",
    group: "On this page",
    description: "Call AXUS APIs with an OAuth access token",
  },
  {
    href: "/developers/playground",
    title: "Request playground",
    group: "Build & explore",
    description: "Generate an authorization URL and inspect PKCE",
  },
  {
    href: "/developers/api",
    title: "GraphQL API explorer",
    group: "Build & explore",
    description: "Queries, mutations and types with the live endpoint",
  },
  {
    href: "/developers/troubleshooting",
    title: "Troubleshooting",
    group: "Resources",
    description:
      "Redirect mismatch, PKCE failed, missing email, CORS and refresh failures",
  },
  {
    href: "/brand",
    title: "Button & brand",
    group: "Resources",
    description: "Continue with AXUS ID logo, styles and assets",
  },
];
