mutation LoginWithPassword($auid: ID!, $password: String!, $permissions: [String!]) {
  loginWithPassword(auid: $auid, password: $password, permissions: $permissions) {
    id
  }
}

mutation CreateUser(
  $contextAuid: ID
  $registrationKey: ID!
) {
  createUser(
    contextAuid: $contextAuid
    registrationKey: $registrationKey
  ) {
    auid
    token {
      id
    }
  }
}

mutation SetPassword(
  $auid: ID!
  $password: String!
) {
  setPassword(auid: $auid, password: $password)
}

query IsPasswordSet($auid: ID!) {
  isPasswordSet(auid: $auid)
}

mutation LoginWithExternalIdentity(
  $authentication: ExternalAuthenticationInput!
  $permissions: [String!]
) {
  loginWithExternalIdentity(
    authentication: $authentication
    permissions: $permissions
  ) {
    id
    auid
  }
}

mutation LinkExternalIdentity(
  $auid: ID!
  $authentication: ExternalAuthenticationInput!
) {
  linkExternalIdentity(
    auid: $auid
    authentication: $authentication
  ) {
    id
    providerId
    createdAt
  }
}

mutation LoginWithToken($auid: ID!, $permissions: [String!]) {
  loginWithToken(auid: $auid, permissions: $permissions) {
    id
  }
}

mutation RevokeToken {
  revokeToken
}
