mutation LoginWithPassword($auid: ID!, $password: String!, $permissions: [String!]) {
  loginWithPassword(auid: $auid, password: $password, permissions: $permissions) {
    id
  }
}

mutation WrapTokenInCredentials($auid: ID!, $tokenId: String) {
  wrapTokenInCredentials(auid: $auid, tokenId: $tokenId) {
    auid
    accessToken
    refreshToken
    accessTokenExpiresAt
  }
}

mutation RefreshCredentials($refreshToken: String!) {
  refreshCredentials(refreshToken: $refreshToken) {
    accessToken
    refreshToken
    accessTokenExpiresAt
  }
}

mutation RevokeCredentials($refreshToken: String!) {
  revokeCredentials(refreshToken: $refreshToken)
}

mutation CreateUser(
  $contextAuid: ID
  $tokenId: String
  $registrationKey: ID!
) {
  createUser(
    contextAuid: $contextAuid
    tokenId: $tokenId
    registrationKey: $registrationKey
  ) {
    auid
    token {
      id
    }
  }
}

mutation SetPassword(
  $auid: ID!
  $tokenId: String
  $password: String!
) {
  setPassword(auid: $auid, tokenId: $tokenId, password: $password)
}

query IsPasswordSet($auid: ID!) {
  isPasswordSet(auid: $auid)
}

mutation LoginWithExternalIdentity(
  $authentication: ExternalAuthenticationInput!
  $permissions: [String!]
) {
  loginWithExternalIdentity(
    authentication: $authentication
    permissions: $permissions
  ) {
    id
    auid
  }
}

mutation LinkExternalIdentity(
  $auid: ID!
  $tokenId: String
  $authentication: ExternalAuthenticationInput!
) {
  linkExternalIdentity(
    auid: $auid
    tokenId: $tokenId
    authentication: $authentication
  ) {
    id
    providerId
    createdAt
  }
}
