query OwnerByUsername($username: String!) {
  ownerByUsername(username: $username)
}

query User($auid: ID!) {
  user(auid: $auid) {
    identity {
      auid
      id
    }
    usernames {
      auid
      usernames
      defaultUsername
    }
    defaultVariation {
      auid
      variationId
    }
  }
}

query Usernames($auid: ID!) {
  usernames(auid: $auid) {
    auid
    usernames
    defaultUsername
  }
}

query Variations($auid: ID!) {
  variations(auid: $auid) {
    id
    auid
    locationId
    icon
    createdAt
  }
}

query Name($variationId: ID!) {
  name(variationId: $variationId) {
    variationId
    displayName
    elements {
      partType
      value
      separatorType
    }
  }
}

query Description($variationId: ID!) {
  description(variationId: $variationId) {
    variationId
    text
    updatedAt
  }
}

query Status($variationId: ID!) {
  status(variationId: $variationId) {
    variationId
    text
    emoji
    expiresAt
    updatedAt
    isExpired
  }
}

query DefaultVariation($auid: ID!) {
  defaultVariation(auid: $auid) {
    auid
    variationId
  }
}

mutation AddUsername($auid: ID!, $tokenId: String, $username: String!) {
  addUsername(auid: $auid, tokenId: $tokenId, username: $username) {
    auid
    usernames
    defaultUsername
  }
}

mutation RemoveUsername($auid: ID!, $username: String!) {
  removeUsername(auid: $auid, username: $username) {
    auid
    usernames
    defaultUsername
  }
}

mutation ChangeDefaultUsername($auid: ID!, $username: String!) {
  changeDefaultUsername(auid: $auid, username: $username) {
    auid
    usernames
    defaultUsername
  }
}

mutation ChangeUsername($auid: ID!, $tokenId: String, $oldUsername: String!, $newUsername: String!) {
  changeUsername(auid: $auid, tokenId: $tokenId, oldUsername: $oldUsername, newUsername: $newUsername) {
    auid
    usernames
    defaultUsername
  }
}

mutation CreateVariation(
  $auid: ID!
  $description: String
  $locationId: String
  $icon: String
) {
  createVariation(
    auid: $auid
    description: $description
    locationId: $locationId
    icon: $icon
  ) {
    id
    auid
    locationId
    icon
    createdAt
  }
}

mutation ChangeName(
  $auid: ID!
  $variationId: ID!
  $elements: [NameElementInput!]!
) {
  changeName(
    auid: $auid
    variationId: $variationId
    elements: $elements
  ) {
    variationId
    displayName
    elements {
      partType
      value
      separatorType
    }
  }
}

mutation ChangeStatus(
  $auid: ID!
  $variationId: ID!
  $text: String
) {
  changeStatus(
    auid: $auid
    variationId: $variationId
    text: $text
  ) {
    variationId
    text
    emoji
    expiresAt
    updatedAt
    isExpired
  }
}

mutation ChangeDescription(
  $auid: ID!
  $variationId: ID!
  $text: String
) {
  changeDescription(
    auid: $auid
    variationId: $variationId
    text: $text
  ) {
    variationId
    text
    updatedAt
  }
}

mutation SetDefaultVariation($auid: ID!, $variationId: ID!) {
  setDefaultVariation(auid: $auid, variationId: $variationId) {
    auid
    variationId
  }
}

query ExternalIdentities($auid: ID!, $tokenId: String) {
  externalIdentities(auid: $auid, tokenId: $tokenId) {
    id
    providerId
    createdAt
  }
}

query ExternalIdentityAccessToken($auid: ID!, $externalIdentityId: ID!, $tokenId: String) {
  externalIdentityAccessToken(auid: $auid, externalIdentityId: $externalIdentityId, tokenId: $tokenId) {
    accessToken
    tokenType
    expiresIn
    scopes
  }
}

mutation UnlinkExternalIdentity($auid: ID!, $externalIdentityId: ID!, $tokenId: String) {
  unlinkExternalIdentity(auid: $auid, externalIdentityId: $externalIdentityId, tokenId: $tokenId)
}


